package tz.go.mnrt.asert.modules.setup.fileupload.enums;

public enum FileUploadType {
    REGISTRATION_CERTIFICATE,
    BPRA_CERTIFICATE,
    MOU,
    DIRECTOR_ZANID,
    TIN_CERTIFICATE,
    ZRA_NUMBER,
    INSPECTION_REPORT,
    INCINERATOR_PICTURE,
    BUILDING_MAP,
    TAEC_LICENSE,

    // Hotel-specific types
    HOTEL_EXTERIOR,
    HOTEL_INTERIOR,
    HOTEL_LOBBY,
    HOTEL_ROOM,
    HOTEL_BATHROOM,
    HOTEL_RESTAURANT,
    HOTEL_BAR,
    HOTEL_POOL,
    HOTEL_GYM,
    HOTEL_SPA,
    HOTEL_CONFERENCE,
    HOTEL_AMENITIES,
    HOTEL_VIEW,
    HOTEL_FLOOR_PLAN,
    HOTEL_LOGO,
    HOTEL_LICENSE,
    COMPLIANCE_DOCUMENTS,
    HOTEL_CERTIFICATE,

    // Assessment Request Document Types
    BUILDING_PLAN_DOCUMENTS,
    OCCUPATIONAL_CERTIFICATE,
    OPERATING_LICENSES,
    EIA_REPORTS_AUDITS,
    DRAINAGE_SYSTEM_DOCS,
    ROOM_DESIGNATION_DOCS,
    SAFE_DEPOSIT_DOCS,
    HAND_WASH_BASIN_DOCS,
    WASH_ROOMS_DOCS,
    WASTE_DISPOSAL_DOCS,
    SEWAGE_DISPOSAL_DOCS,
    SWIMMING_POOL_DOCS,
    SEWAGE_SYSTEM_DOCS,
    WATER_SUPPLY_DOCS,
    SOLID_WASTE_DOCS,
    VENTILATION_SYSTEM_DOCS,
    KITCHEN_FACILITIES_DOCS,
    FIRE_EXTINGUISHER_DOCS,
    ESCAPE_ROUTES_DOCS,
    SECURITY_MEASURES_DOCS,
    LIGHTING_SYSTEM_DOCS,
    EMERGENCY_EQUIPMENT_DOCS,
    ELECTRICITY_SUPPLY_DOCS,
    TELECOMMUNICATION_DOCS,
    LAUNDRY_SERVICES_DOCS,
    INTERNET_SERVICES_DOCS,
    TRANSPORT_SERVICES_DOCS,
    QUALIFIED_STAFF_DOCS,
    HEALTH_SAFETY_DOCS,
    VERMIN_PROOFING_DOCS,
    FIRE_SAFETY_DOCS,
    SECURITY_SYSTEMS_DOCS,
    COMMUNICATION_SYSTEMS_DOCS,
    ELECTRICAL_SAFETY_DOCS,
    FIRST_AID_DOCS,
    QUALIFIED_MANAGEMENT_DOCS,
    QUALIFIED_MANAGEMENT_STAFF_DOCS,
    QUALIFIED_HEADS_DOCS,
    QUALIFIED_DEPARTMENTAL_HEADS_DOCS,
    HEALTH_MEDICAL_DOCS,
    HEALTH_MEDICAL_EXAM_DOCS,
    EMERGENCY_EVACUATION_DOCS,
    INSURANCE_DOCS,

    // Assessor certificate types
    ASSESSOR_CERTIFICATE,
    ASSESSOR_TRANSCRIPT,
    ASSESSOR_VERIFICATION_LETTER,

    PROFILE_PHOTO;

    public static boolean isValidType(String s) {
        for (FileUploadType uploadType : values()) {
            if (uploadType.name().equals(s))
                return true;
        }
        return false;
    }
}
