package tz.go.mnrt.asert.enums;

public enum Status {
    ACTIVE,
    INACTIVE,
    DEPRICATED,
    PENDING,
    PAID,
    CANCELLED,
    AWAITING_APPLICATION_FEES,
    APPLICATION_EXPIRED,
    AWAITING_INSPECTION,
    INSPECTION_FAILED,
    APPROVAL_FAILED,
    AWAITING_REGISTRATION_FEES,
    REGISTRATION_EXPIRED,
    REGISTERED,
    NOTIFIED
}
