-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
CREATE TABLE entity_trackers
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action         VARCHAR(255)                            NOT NULL,
    trackable_type VARCHAR(255)                            NOT NULL,
    trackable_id   BIGINT                                  NOT NULL,
    state          VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by     VARCHAR(255),
    CONSTRAINT pk_entity_tracker PRIMARY KEY (id)
);

CREATE TABLE wfis_reports
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    name       VARCHAR(255),
    url        VARCHAR(255),
    parent_id  BIGINT,
    CONSTRAINT pk_wfis_reports PRIMARY KEY (id)
);

ALTER TABLE wfis_reports
    ADD CONSTRAINT uc_wfis_reports_uuid UNIQUE (uuid);

ALTER TABLE wfis_reports
    ADD CONSTRAINT FK_WFIS_REPORTS_ON_PARENT FOREIGN KEY (parent_id) REFERENCES wfis_reports (id);

CREATE TABLE authorities
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    name       VARCHAR(255)                            NOT NULL,
    resource   VARCHAR(255),
    action     VARCHAR(255),
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

ALTER TABLE authorities
    ADD CONSTRAINT uc_authorities_uuid UNIQUE (uuid);

CREATE TABLE financial_years
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    name       VARCHAR(255)                            NOT NULL,
    start_date date                                    NOT NULL,
    end_date   date                                    NOT NULL,
    is_current BOOLEAN,
    CONSTRAINT pk_financial_years PRIMARY KEY (id)
);

ALTER TABLE financial_years
    ADD CONSTRAINT uc_financial_years_uuid UNIQUE (uuid);

CREATE TABLE menu_groups
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID                                    NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    name              VARCHAR(255),
    icon              VARCHAR(255),
    state             VARCHAR(255),
    sort_order        INTEGER,
    translation_label VARCHAR(255),
    CONSTRAINT pk_menu_groups PRIMARY KEY (id)
);

ALTER TABLE menu_groups
    ADD CONSTRAINT uc_menu_groups_uuid UNIQUE (uuid);

CREATE TABLE menu_item_authorities
(
    authority_id BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    CONSTRAINT pk_menu_item_authorities PRIMARY KEY (authority_id, menu_item_id)
);

CREATE TABLE menu_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID                                    NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    name              VARCHAR(255)                            NOT NULL,
    icon              VARCHAR(255),
    state             VARCHAR(255)                            NOT NULL,
    sort_order        INTEGER,
    translation_label VARCHAR(255),
    menu_group_id     BIGINT,
    CONSTRAINT pk_menu_items PRIMARY KEY (id)
);

ALTER TABLE menu_items
    ADD CONSTRAINT uc_menu_items_state UNIQUE (state);

ALTER TABLE menu_items
    ADD CONSTRAINT uc_menu_items_uuid UNIQUE (uuid);

ALTER TABLE menu_items
    ADD CONSTRAINT FK_MENU_ITEMS_ON_MENU_GROUP FOREIGN KEY (menu_group_id) REFERENCES menu_groups (id);

ALTER TABLE menu_item_authorities
    ADD CONSTRAINT fk_meniteaut_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id);

ALTER TABLE menu_item_authorities
    ADD CONSTRAINT fk_meniteaut_on_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items (id);

CREATE TABLE role_authorities
(
    authority_id BIGINT NOT NULL,
    role_id      BIGINT NOT NULL,
    CONSTRAINT pk_role_authorities PRIMARY KEY (authority_id, role_id)
);

CREATE TABLE admin_hierarchy_levels
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    name       VARCHAR(255)                            NOT NULL,
    code       VARCHAR(255)                            NOT NULL,
    position   INTEGER                                 NOT NULL,
    CONSTRAINT pk_admin_hierarchy_levels PRIMARY KEY (id)
);

ALTER TABLE admin_hierarchy_levels
    ADD CONSTRAINT uc_admin_hierarchy_levels_code UNIQUE (code);

ALTER TABLE admin_hierarchy_levels
    ADD CONSTRAINT uc_admin_hierarchy_levels_name UNIQUE (name);

ALTER TABLE admin_hierarchy_levels
    ADD CONSTRAINT uc_admin_hierarchy_levels_position UNIQUE (position);

ALTER TABLE admin_hierarchy_levels
    ADD CONSTRAINT uc_admin_hierarchy_levels_uuid UNIQUE (uuid);

CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    name       VARCHAR(255),
    code       VARCHAR(255),
    level_id   BIGINT,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_code UNIQUE (code);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_uuid UNIQUE (uuid);

ALTER TABLE roles
    ADD CONSTRAINT FK_ROLES_ON_LEVEL FOREIGN KEY (level_id) REFERENCES admin_hierarchy_levels (id);

ALTER TABLE role_authorities
    ADD CONSTRAINT fk_rolaut_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id);

ALTER TABLE role_authorities
    ADD CONSTRAINT fk_rolaut_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

CREATE TABLE admin_hierarchies
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                     UUID                                    NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    created_by               VARCHAR(255),
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_by               VARCHAR(255),
    name                     VARCHAR(255)                            NOT NULL,
    code                     VARCHAR(255)                            NOT NULL,
    admin_hierarchy_level_id BIGINT,
    parent_id                BIGINT,
    CONSTRAINT pk_admin_hierarchies PRIMARY KEY (id)
);

ALTER TABLE admin_hierarchies
    ADD CONSTRAINT uc_admin_hierarchies_code UNIQUE (code);

ALTER TABLE admin_hierarchies
    ADD CONSTRAINT uc_admin_hierarchies_uuid UNIQUE (uuid);

ALTER TABLE admin_hierarchies
    ADD CONSTRAINT FK_ADMIN_HIERARCHIES_ON_ADMIN_HIERARCHY_LEVEL FOREIGN KEY (admin_hierarchy_level_id) REFERENCES admin_hierarchy_levels (id);

ALTER TABLE admin_hierarchies
    ADD CONSTRAINT FK_ADMIN_HIERARCHIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES admin_hierarchies (id);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID                                    NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          VARCHAR(255),
    email               VARCHAR(255)                            NOT NULL,
    password            VARCHAR(255)                            NOT NULL,
    first_name          VARCHAR(255)                            NOT NULL,
    middle_name         VARCHAR(255),
    last_name           VARCHAR(255),
    sex                 VARCHAR(255),
    mobile_number       VARCHAR(255),
    is_active           BOOLEAN,
    is_client           BOOLEAN,
    password_changed    BOOLEAN,
    admin_hierarchy_id  BIGINT,
    department_id       BIGINT,
    collection_point_id BIGINT,
    full_name           VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_uuid UNIQUE (uuid);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ADMIN_HIERARCHY FOREIGN KEY (admin_hierarchy_id) REFERENCES admin_hierarchies (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);