-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE file_uploads
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                    UUID                                    NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    created_by              VARCHAR(255),
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    is_deleted              BOOLEAN DEFAULT FALSE,
    updated_by              VARCHAR(255),

    user_id                 BIGINT DEFAULT NULL,
    file_path               VARCHAR(255)                            NOT NULL,
    file_type               VARCHAR(255)                            NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    upload_type             VARCHAR(255)                            NOT NULL,
    file_size               BIGINT,
    CONSTRAINT pk_file_uploads  PRIMARY KEY (id)
);


ALTER TABLE file_uploads
    ADD CONSTRAINT uc_file_uploads_uuid UNIQUE (uuid);


ALTER TABLE file_uploads
    ADD CONSTRAINT FK_FILE_UPLOAD_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
