-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
CREATE TABLE translations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid          UUID                                    NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_by    VARCHAR(255),
    display_label VARCHAR(255),
    english       VARCHAR(255),
    swahili       VARCHAR(255),
    CONSTRAINT pk_translations PRIMARY KEY (id)
);

ALTER TABLE translations
    ADD CONSTRAINT uc_translations_displaylabel UNIQUE (display_label);

ALTER TABLE translations
    ADD CONSTRAINT uc_translations_english UNIQUE (english);

ALTER TABLE translations
    ADD CONSTRAINT uc_translations_swahili UNIQUE (swahili);

ALTER TABLE translations
    ADD CONSTRAINT uc_translations_uuid UNIQUE (uuid);