
CREATE TABLE services
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name                varchar(255)                           not null,
    code                varchar(32)                            not null unique,
    service_category_id         BIGINT                         NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_services PRIMARY KEY (id)
);

ALTER TABLE services
    ADD CONSTRAINT uc_services_uuid UNIQUE (uuid);

ALTER TABLE services
    ADD CONSTRAINT FK_services_ON_service_category FOREIGN KEY (service_category_id) REFERENCES service_categories (id);

