
CREATE TABLE order_premises
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    premise_number          INTEGER NOT NULL,
    order_id                BIGINT NOT NULL,
    premise_id              BIGINT NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_order_premises PRIMARY KEY (id)
);

ALTER TABLE order_premises
    ADD CONSTRAINT uc_order_premises_uuid UNIQUE (uuid);

 ALTER TABLE order_premises
     ADD CONSTRAINT FK_order_premises_ON_order FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_premises
    ADD CONSTRAINT FK_order_premises_ON_premise FOREIGN KEY (premise_id) REFERENCES premises (id);
