-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration has been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE api_key_metadata
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    -- ADD YOUR COLUMNS HERE
    api_key_id         BIGINT                                  NOT NULL,
    last_used_at       TIMESTAMP WITHOUT TIME ZONE,
    usage_count        BIGINT                                  DEFAULT 0,
    created_ip         INET,
    allowed_ips        JSON,
    rate_limit         INTEGER                                 DEFAULT 1000,
    rate_limit_reset   TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),  -- Added this line
    -- ADD YOUR COLUMNS HERE

    CONSTRAINT pk_api_key_metadata PRIMARY KEY (id),
    CONSTRAINT fk_api_key_metadata_api_key FOREIGN KEY (api_key_id) REFERENCES api_keys(id)
);

ALTER TABLE api_key_metadata
    ADD CONSTRAINT uc_api_key_metadata_uuid UNIQUE (uuid);

