-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.


-----DELETE ME TO APPLY THIS MIGRATION----

DROP TABLE IF EXISTS order_attachments;

CREATE TABLE order_attachments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    -- ADD YOUR COLUMNS HERE
    order_id           BIGINT NOT NULL,
    name               VARCHAR(255),
    attachmment_id     BIGINT NOT NULL,

    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_order_attachments PRIMARY KEY (id)
);

ALTER TABLE order_attachments
    ADD CONSTRAINT uc_order_attachments_uuid UNIQUE (uuid);


ALTER TABLE order_attachments
    ADD CONSTRAINT FK_ORDER_ATTACHMENTS_ON_FILE_UPLOADS FOREIGN KEY (attachmment_id) REFERENCES file_uploads (id);
