
CREATE TABLE bill_types
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name                                    VARCHAR(255)                 NOT NULL,
    code                                    VARCHAR(255)                 NOT NULL,
    rate                                    NUMERIC(32,2)                NOT NULL,
    description                             VARCHAR(255)                 NOT NULL,
    expiration_date                         DATE,
    effective_date                          DATE,
    is_partial                              BOOLEAN,
    status                                  VARCHAR(255)                 NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_bill_types PRIMARY KEY (id)
);

ALTER TABLE bill_types
    ADD CONSTRAINT uc_bill_types_uuid UNIQUE (uuid);
