
CREATE TABLE facility_staffs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    facility_id        BIGINT                           NOT NULL,
    staff_title_id     BIGINT                           NOT NULL,
    staff_id           BIGINT                          NOT NULL,
    department         VARCHAR(32)                      NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_facility_staffs PRIMARY KEY (id)
);

ALTER TABLE facility_staffs
    ADD CONSTRAINT uc_facility_staffs_uuid UNIQUE (uuid);

ALTER TABLE facility_staffs
    ADD CONSTRAINT FK_facility_staffs_ON_facility FOREIGN KEY (facility_id) REFERENCES facilities (id);

ALTER TABLE facility_staffs
    ADD CONSTRAINT FK_facility_staffs_ON_staff_title FOREIGN KEY (staff_title_id) REFERENCES staff_titles (id);

ALTER TABLE facility_staffs
    ADD CONSTRAINT FK_facility_staffs_ON_staff FOREIGN KEY (staff_id) REFERENCES staffs (id);

