

CREATE TABLE facility_infrastructures
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name                         VARCHAR(255)                            NOT NULL,
    label_number                 VARCHAR(255)                            NOT NULL UNIQUE,
    infrastructure_id            BIGINT                                  NOT NULL,
    facility_id                  BIGINT                                  NOT NULL,
    number_of_storeys            INTEGER,
    construction_start_date      DATE,
    construction_end_date        DATE,
    purchase_date                DATE,
    infrastructure_condition     VARCHAR(255),
    is_functional                BOOLEAN,
    date_of_last_maintenance     DATE,
    supplier_contractor          VARCHAR(255),
    liability_warrant_end_date   DATE,
    serial_no                    VARCHAR(255),
    is_asset_movable             BOOLEAN,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_facility_infrastructures PRIMARY KEY (id)
);

ALTER TABLE facility_infrastructures
    ADD CONSTRAINT uc_facility_infrastructures_uuid UNIQUE (uuid);

ALTER TABLE facility_infrastructures
    ADD CONSTRAINT FK_facility_infrastructures_ON_infrastructures FOREIGN KEY (infrastructure_id) REFERENCES infrastructures (id);

ALTER TABLE facility_infrastructures
    ADD CONSTRAINT FK_facility_infrastructures_ON_facility FOREIGN KEY (facility_id) REFERENCES facilities (id);
