
CREATE TABLE facility_equipments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    facility_id                             BIGINT                       NOT NULL,
    equipment_id                            BIGINT                       NOT NULL,
    equipment_number                        INTEGER                      NOT NULL,
    non_equipment_number                    INTEGER,
    under_maintenance_equipment_number      INTEGER,
    bed_capacity                            INTEGER,
    is_active                               BOOLEAN,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_facility_equipments PRIMARY KEY (id)
);

ALTER TABLE facility_equipments
    ADD CONSTRAINT uc_facility_equipments_uuid UNIQUE (uuid);

ALTER TABLE facility_equipments
    ADD CONSTRAINT FK_facility_equipments_ON_facility FOREIGN KEY (facility_id) REFERENCES facilities (id);

ALTER TABLE facility_equipments
    ADD CONSTRAINT FK_facility_equipments_ON_equipment FOREIGN KEY (equipment_id) REFERENCES equipments (id);
