-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE state_role_states
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    state_role_id BIGINT NOT NULL,
    state VARCHAR(255) NOT NULL,

    CONSTRAINT pk_state_role_states PRIMARY KEY (state_role_id, state),
    CONSTRAINT fk_state_role_states_state_role_id FOREIGN KEY (state_role_id) REFERENCES state_roles(id)
);
