
CREATE TABLE companies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    company_name                     VARCHAR(255)                NOT NULL,
    initials                         VARCHAR(255)                NOT NULL,
    company_type_id                  BIGINT                      NOT NULL,
    admin_hierarchy_id               BIGINT                      NOT NULL,
    registration_number              VARCHAR(255)                NOT NULL,
    BPRA_cetrificate_number          VARCHAR(255)                NOT NULL,
    responsible_first_name           VARCHAR(255)                NOT NULL,
    responsible_middle_name          VARCHAR(255)                NOT NULL,
    responsible_last_name            VARCHAR(255)                NOT NULL,
    responsible_phone                VARCHAR(255)                NOT NULL,
    responsible_email               VARCHAR(255)                NOT NULL,
    is_active                       BOOLEAN,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_uuid UNIQUE (uuid);

ALTER TABLE companies
    ADD CONSTRAINT FK_companies_ON_company_type FOREIGN KEY (company_type_id) REFERENCES company_types (id);

ALTER TABLE companies
    ADD CONSTRAINT FK_companies_ON_admin_hierarchy FOREIGN KEY (admin_hierarchy_id) REFERENCES admin_hierarchies (id);
