-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.


-----DELETE ME TO APPLY THIS MIGRATION----

CREATE TABLE pre_registrations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    proposed_name                       varchar(255) NOT NULL,
    admin_hierarchy_id                  BIGINT,
    proposed_facility_level_id          BIGINT,
    nearest_facility_id                 BIGINT,
    user_id                             BIGINT,
    is_approved                         BOOLEAN,

    CONSTRAINT pk_pre_registrations PRIMARY KEY (id)
);

ALTER TABLE pre_registrations
    ADD CONSTRAINT uc_pre_registrations_uuid UNIQUE (uuid);
