
CREATE TABLE facility_premises
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    facility_id                           BIGINT                       NOT NULL,
    premise_id                            BIGINT                       NOT NULL,
    premise_number                        INTEGER                      NOT NULL,
    is_active                             BOOLEAN,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_facility_premises PRIMARY KEY (id)
);

ALTER TABLE facility_premises
    ADD CONSTRAINT uc_facility_premises_uuid UNIQUE (uuid);

ALTER TABLE facility_premises
    ADD CONSTRAINT FK_facility_premises_ON_facility FOREIGN KEY (facility_id) REFERENCES facilities (id);

ALTER TABLE facility_premises
    ADD CONSTRAINT FK_facility_premises_ON_premise FOREIGN KEY (premise_id) REFERENCES premises (id);
