-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migrations have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- 1. Create the table for change_requests
CREATE EXTENSION pgcrypto;

CREATE TABLE change_requests
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            UUID                        DEFAULT gen_random_uuid(),
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_by      VARCHAR(255),
    is_deleted      BOOLEAN                     DEFAULT FALSE,
    facility_id     BIGINT      NOT NULL,
    changeable_type VARCHAR(50) NOT NULL,
    changeable_id   BIGINT      NOT NULL,
    CONSTRAINT fk_facility FOREIGN KEY (facility_id) REFERENCES facilities (id)
);

-- 2. Create the table for location_changes
CREATE TABLE location_changes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_location_admin_hierarchy FOREIGN KEY (location_id) REFERENCES admin_hierarchies (id)
);

-- 3. Create the table for ownership_changes
CREATE TABLE ownership_changes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ownership_id BIGINT NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ownership_facility_ownership_authority FOREIGN KEY (ownership_id) REFERENCES facility_ownership_authorities (id)
);

-- 4. Create indexes for faster lookups
CREATE INDEX idx_change_requests_changeable ON change_requests (changeable_type, changeable_id);

-- 5. Add comments for clarity
COMMENT ON TABLE change_requests IS 'Table for managing change requests for facilities with polymorphic support';
COMMENT ON COLUMN change_requests.changeable_type IS 'Type of change (e.g., LOCATION or OWNERSHIP)';
COMMENT ON COLUMN change_requests.changeable_id IS 'ID of the associated changeable entity (e.g., LocationChange or OwnershipChange)';
COMMENT ON TABLE location_changes IS 'Table for storing location change requests for facilities, linked to AdminHierarchy';
COMMENT ON TABLE ownership_changes IS 'Table for storing ownership change requests for facilities, linked to FacilityOwnershipAuthority';

