
CREATE TABLE order_equipments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    equipment_number                        varchar(255) NOT NULL,
    non_equipment_number                    varchar(32),
    under_maintenance_equipment_number      varchar(255),
    capacity_number                         INTEGER,
    order_id                                BIGINT NOT NULL,
    equipment_id                            BIGINT NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_order_equipments PRIMARY KEY (id)
);

ALTER TABLE order_equipments
    ADD CONSTRAINT uc_order_equipments_uuid UNIQUE (uuid);

ALTER TABLE order_equipments
    ADD CONSTRAINT FK_order_equipments_ON_order FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_equipments
    ADD CONSTRAINT FK_order_equipments_ON_equipment FOREIGN KEY (equipment_id) REFERENCES equipments (id);
