-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE IF NOT EXISTS facility_level_equipments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID UNIQUE                             NOT NULL,
    quantity          float                                   NOT NULL DEFAULT 0.0,
    equipment_id      BIGINT                                  not null,
    facility_level_id BIGINT                                  not null,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    is_deleted        BOOLEAN,
    CONSTRAINT pk_facility_level_equipments PRIMARY KEY (id),
    CONSTRAINT fk_equipment_id_on_equipments FOREIGN KEY (equipment_id) REFERENCES equipments (id) on delete cascade on update cascade,
    CONSTRAINT fk_facility_level_id_on_equipments FOREIGN KEY (facility_level_id) REFERENCES facility_levels (id) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS facility_level_premises
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID UNIQUE                             NOT NULL,
    quantity          float                                   NOT NULL DEFAULT 0.0,
    premise_id        BIGINT                                  not null,
    facility_level_id BIGINT                                  not null,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    is_deleted        BOOLEAN,
    CONSTRAINT pk_facility_level_premises PRIMARY KEY (id),
    CONSTRAINT fk_premise_id_on_premises FOREIGN KEY (premise_id) REFERENCES premises (id) on delete cascade on update cascade,
    CONSTRAINT fk_facility_level_id_on_premises FOREIGN KEY (facility_level_id) REFERENCES facility_levels (id) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS facility_level_infrastructures
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID UNIQUE                             NOT NULL,
    quantity          float                                   NOT NULL DEFAULT 0.0,
    infrastructure_id BIGINT                                  not null,
    facility_level_id BIGINT                                  not null,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    is_deleted        BOOLEAN,
    CONSTRAINT pk_facility_level_infrastructures PRIMARY KEY (id),
    CONSTRAINT fk_infrastructure_id_on_infrastructures FOREIGN KEY (infrastructure_id) REFERENCES infrastructures (id) on delete cascade on update cascade,
    CONSTRAINT fk_facility_level_id_on_infrastructures FOREIGN KEY (facility_level_id) REFERENCES facility_levels (id) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS facility_level_staff_titles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID UNIQUE                             NOT NULL,
    quantity          float                                   NOT NULL DEFAULT 0.0,
    staff_title_id    BIGINT                                  not null,
    facility_level_id BIGINT                                  not null,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    is_deleted        BOOLEAN,
    CONSTRAINT pk_facility_level_staff_titles PRIMARY KEY (id),
    CONSTRAINT fk_staff_title_id_on_staff_titles FOREIGN KEY (staff_title_id) REFERENCES staff_titles (id) on delete cascade on update cascade,
    CONSTRAINT fk_facility_level_id_on_staff_titles FOREIGN KEY (facility_level_id) REFERENCES facility_levels (id) on delete cascade on update cascade
);
