
CREATE TABLE staffs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    first_name              VARCHAR(255)   NOT NULL,
    middle_name             VARCHAR(255)   NOT NULL,
    last_name               VARCHAR(255)   NOT NULL,
    sex                     VARCHAR(255)   NOT NULL,
    license_number          VARCHAR(255)   NOT NULL UNIQUE,
    qualification           VARCHAR(255)   NOT NULL,
    mobile_phone            VARCHAR(255)   NOT NULL UNIQUE,
    email                   VARCHAR(255),

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_staffs PRIMARY KEY (id)
);

ALTER TABLE staffs
    ADD CONSTRAINT uc_staffs_uuid UNIQUE (uuid);
