

CREATE TABLE service_categories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name       varchar(255)                            not null,
    code       varchar(32)                             not null unique,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_service_categories PRIMARY KEY (id)
);

ALTER TABLE service_categories
    ADD CONSTRAINT uc_service_categories_uuid UNIQUE (uuid);
