CREATE TABLE notification_types
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name               VARCHAR(75)                             NOT NULL,
    description        VARCHAR(255),
    code               VARCHAR(20)                             NOT NULL,
    is_active          BOOLEAN,

    -- ADD YOUR COLUMNS HERE

    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_notification_types PRIMARY KEY (id)
);

ALTER TABLE notification_types
    ADD CONSTRAINT uc_notification_types_uuid UNIQUE (uuid);
