
CREATE TABLE applications
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    user_id                     BIGINT                      NOT NULL,
    facility_id                 BIGINT                      NOT NULL,
    company_id                  BIGINT                      NOT NULL,
    application_type_id         BIGINT                      NOT NULL,
    application_status          VARCHAR(255)                NOT NULL,
    financial_year_id           BIGINT,
    submitted                   BOOLEAN,
    is_approved                 BOOLEAN,
    is_active                   BOOLEAN,
    application_approval        VARCHAR(255)                NOT NULL,
    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_applications PRIMARY KEY (id)
);

ALTER TABLE applications
    ADD CONSTRAINT uc_applications_uuid UNIQUE (uuid);

ALTER TABLE applications
    ADD CONSTRAINT FK_applications_ON_company FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE applications
    ADD CONSTRAINT FK_applications_ON_application_type FOREIGN KEY (application_type_id) REFERENCES application_types (id);
