-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE state_roles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    role_id            BIGINT                                  NOT NULL, 

    CONSTRAINT pk_state_roles PRIMARY KEY (id),
    CONSTRAINT uc_state_roles_uuid UNIQUE (uuid),
    CONSTRAINT fk_state_roles_role_id FOREIGN KEY (role_id) REFERENCES roles(id)
);

