-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE staff_change_requests
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    facility_id        BIGINT                           NOT NULL,
    staff_title_id     BIGINT                           NOT NULL,
    staff_id           BIGINT                          NOT NULL,
    is_full_time BOOLEAN DEFAULT FALSE,
    change_request_id                       BIGINT                       NOT NULL,
    department         VARCHAR(32)                      NOT NULL,

    -- ADD YOUR COLUMNS HERE

    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_staff_change_requests PRIMARY KEY (id)
);

ALTER TABLE staff_change_requests
    ADD CONSTRAINT uc_staff_change_requests_uuid UNIQUE (uuid);

ALTER TABLE staff_change_requests
    ADD CONSTRAINT FK_staff_change_requests_ON_facility FOREIGN KEY (facility_id) REFERENCES facilities (id);

ALTER TABLE staff_change_requests
    ADD CONSTRAINT FK_staff_change_requests_ON_staff_title FOREIGN KEY (staff_title_id) REFERENCES staff_titles (id);

ALTER TABLE staff_change_requests
    ADD CONSTRAINT FK_staff_change_requests_ON_staff FOREIGN KEY (staff_id) REFERENCES staffs (id);

ALTER TABLE staff_change_requests
    ADD CONSTRAINT FK_staff_change_requests_ON_change_request FOREIGN KEY (change_request_id) REFERENCES change_requests (id);
