-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.


CREATE TABLE order_infrastructures
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name                                varchar(255) NOT NULL,
    label_number                        varchar(32),
    number_of_storeys                   INTEGER,
    construction_start_date             DATE,
    construction_end_date               DATE,
    purchase_date                       DATE,
    infrastructure_condition            varchar(255),
    is_functional                       BOOLEAN,
    date_of_last_maintenance            DATE,
    supplier_contractor                 varchar(255),
    liability_warrant_end_date          DATE,
    serial_no                           VARCHAR(255),
    is_asset_movable                    BOOLEAN,
    order_id                            BIGINT NOT NULL,
    infrastructure_id                   BIGINT NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_order_infrastructures PRIMARY KEY (id)
);

ALTER TABLE order_infrastructures
    ADD CONSTRAINT uc_order_infrastructures_uuid UNIQUE (uuid);

ALTER TABLE order_infrastructures
    ADD CONSTRAINT FK_order_order_infrastructures_ON_order FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_infrastructures
    ADD CONSTRAINT FK_order_order_infrastructures_ON_infrastructure FOREIGN KEY (infrastructure_id) REFERENCES infrastructures (id);
