-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE pre_registration_infrastructure_requirements
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID UNIQUE                             NOT NULL,
    quantity            float                                   NOT NULL DEFAULT 0.0,
    actual_quantity     float                                   NULL     DEFAULT 0.0,
    infrastructure_id   BIGINT                                  not null,
    pre_registration_id BIGINT                                  not null,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          VARCHAR(255),
    is_deleted          BOOLEAN,
    CONSTRAINT pk_pre_registration_infrastructure_requirements PRIMARY KEY (id),
    CONSTRAINT fk_pre_registration_on_pre_registration_inf_requirements FOREIGN KEY (pre_registration_id) REFERENCES pre_registrations (id) on delete cascade on update cascade,
    CONSTRAINT fk_service_on_pre_registration_infrastructure_requirements FOREIGN KEY (infrastructure_id) REFERENCES infrastructures (id) on delete cascade on update cascade
);
