
CREATE TABLE level_groups
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name         VARCHAR(30),
    code         VARCHAR(30),

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_level_groups PRIMARY KEY (id)
);

ALTER TABLE level_groups
    ADD CONSTRAINT uc_level_groups_uuid UNIQUE (uuid);
