
CREATE TABLE bills
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    user_id                           BIGINT                        NOT NULL,
    bill_type_id                      BIGINT                        NOT NULL,
    sp_code                           VARCHAR(255)                  NOT NULL,
    number                            VARCHAR(255)                  NOT NULL,
    description                       VARCHAR(255)                  NOT NULL,
    amount                            NUMERIC(32,2),
    due_date                          DATE,
    generation_date                   DATE                          NOT NULL,
    expiry_date                       DATE,
    paid_date                         DATE,
    status                            VARCHAR(255)                  NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_bills PRIMARY KEY (id)
);

ALTER TABLE bills
    ADD CONSTRAINT uc_bills_uuid UNIQUE (uuid);

ALTER TABLE bills
    ADD CONSTRAINT FK_bills_ON_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE bills
    ADD CONSTRAINT FK_bills_ON_bill_type FOREIGN KEY (bill_type_id) REFERENCES bill_types (id);
