
CREATE TABLE order_staffs
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID                                    NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    is_deleted        BOOLEAN,
    department        varchar(255) NOT NULL,
    order_id          BIGINT NOT NULL,
    staff_id          BIGINT NOT NULL,
    title_id          BIGINT NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_order_staffs PRIMARY KEY (id)
);

ALTER TABLE order_staffs
ADD CONSTRAINT uc_order_staffs_uuid UNIQUE (uuid);

ALTER TABLE order_staffs
ADD CONSTRAINT FK_order_staffs_ON_order FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_staffs
ADD CONSTRAINT FK_order_staffs_ON_staff FOREIGN KEY (staff_id) REFERENCES staffs (id);

ALTER TABLE order_staffs
ADD CONSTRAINT FK_order_staffs_ON_title FOREIGN KEY (title_id) REFERENCES staff_titles (id);

