
CREATE TABLE staff_titles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name                varchar(255)                           NOT NULL,
    code                varchar(32)                            NOT NULL unique,
    is_medical_staff      BOOLEAN                                 NOT NULL,
    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_staff_titles PRIMARY KEY (id)
);

ALTER TABLE staff_titles
    ADD CONSTRAINT uc_staff_titles_uuid UNIQUE (uuid);
