
CREATE TABLE facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    is_deleted BOOLEAN,
    name varchar(255) NOT NULL,
    code varchar(32) NOT NULL unique,
    common_name varchar(255),
    fbo_denomination varchar(32),
    official_phone_no varchar(255) NOT NULL,
    email varchar(32) NOT NULL unique,
    postal_address varchar(255) NOT NULL,
    postal_code varchar(32) NOT NULL,
    website varchar(32) NOT NULL,
    operation_start_date DATE,
    last_re_registration_date DATE,
    expected_start_date DATE,
    landmark varchar(32),
    nearest_facility_distance_km varchar(32),
    service_area_location_id BIGINT NOT NULL,
    service_population varchar(32),
    catchment_area varchar(255) NOT NULL,
    catchment_population varchar(32),
    ref_hosp_id BIGINT,
    ref_hosp_distance_km INTEGER,
    ref_hosp_owner varchar(32),
    referral_point_challenges varchar(255),
    hmis_number varchar(32) NOT NULL unique,
    ctc_number varchar(32),
    registrar_number varchar(255) NOT NULL unique,
    cms_number varchar(32) NOT NULL unique,
    is_board_active BOOLEAN,
    is_designated BOOLEAN,
    hfr_code varchar(32) NOT NULL unique,
    is_open_weekend BOOLEAN,
    is_open_full_day BOOLEAN,
    is_open_holiday BOOLEAN,
    is_open_late_night BOOLEAN,
    latitude FLOAT,
    longitude FLOAT,

    CONSTRAINT pk_facilities PRIMARY KEY (id)
);

ALTER TABLE facilities
ADD CONSTRAINT uc_facilities_uuid UNIQUE(uuid);

ALTER TABLE facilities
ADD CONSTRAINT FK_facilities_ON_adminHierarchy FOREIGN KEY (service_area_location_id) REFERENCES admin_hierarchies (id);
