-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

ALTER TABLE pre_registrations
    ADD COLUMN fund_source_id BIGINT null;

ALTER TABLE pre_registrations
    ADD COLUMN ownership_category_id BIGINT null;

ALTER TABLE pre_registrations
    ADD COLUMN ownership_authority_id BIGINT null;

ALTER TABLE pre_registrations
    ADD COLUMN operating_status_id BIGINT null;


CREATE TABLE pre_registration_service_requirements
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID UNIQUE                             NOT NULL,
    quantity            float                                   NOT NULL DEFAULT 0.0,
    actual_quantity     float                                   NULL     DEFAULT 0.0,
    service_id          BIGINT                                  not null,
    pre_registration_id BIGINT                                  not null,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          VARCHAR(255),
    is_deleted          BOOLEAN,
    CONSTRAINT pk_pre_registration_service_requirements PRIMARY KEY (id),
    CONSTRAINT fk_pre_registration_on_pre_registration_service_requirements FOREIGN KEY (pre_registration_id) REFERENCES pre_registrations (id) on delete cascade on update cascade,
    CONSTRAINT fk_service_on_pre_registration_service_requirements FOREIGN KEY (service_id) REFERENCES services (id) on delete cascade on update cascade
);


CREATE TABLE pre_registration_equipment_requirements
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID UNIQUE                             NOT NULL,
    quantity            float                                   NOT NULL DEFAULT 0.0,
    actual_quantity     float                                   NULL     DEFAULT 0.0,
    equipment_id        BIGINT                                  not null,
    pre_registration_id BIGINT                                  not null,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          VARCHAR(255),
    is_deleted          BOOLEAN,
    CONSTRAINT pk_pre_registration_equipment_requirements PRIMARY KEY (id),
    CONSTRAINT fk_pre_registration_on_pre_registration_equipment_requirements FOREIGN KEY (pre_registration_id) REFERENCES pre_registrations (id) on delete cascade on update cascade,
    CONSTRAINT fk_service_on_pre_registration_equipment_requirements FOREIGN KEY (equipment_id) REFERENCES equipments (id) on delete cascade on update cascade
);

CREATE TABLE pre_registration_premise_requirements
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID UNIQUE                             NOT NULL,
    quantity            float                                   NOT NULL DEFAULT 0.0,
    actual_quantity     float                                   NULL     DEFAULT 0.0,
    premise_id          BIGINT                                  not null,
    pre_registration_id BIGINT                                  not null,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          VARCHAR(255),
    is_deleted          BOOLEAN,
    CONSTRAINT pk_pre_registration_premise_requirements PRIMARY KEY (id),
    CONSTRAINT fk_pre_registration_on_pre_registration_premise_requirements FOREIGN KEY (pre_registration_id) REFERENCES pre_registrations (id) on delete cascade on update cascade,
    CONSTRAINT fk_service_on_pre_registration_premise_requirements FOREIGN KEY (premise_id) REFERENCES premises (id) on delete cascade on update cascade
);

CREATE TABLE pre_registration_staff_requirements
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID UNIQUE                             NOT NULL,
    quantity            float                                   NOT NULL DEFAULT 0.0,
    actual_quantity     float                                   NULL     DEFAULT 0.0,
    staff_id            BIGINT                                  not null,
    pre_registration_id BIGINT                                  not null,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          VARCHAR(255),
    is_deleted          BOOLEAN,
    CONSTRAINT pk_pre_registration_staff_requirements PRIMARY KEY (id),
    CONSTRAINT fk_pre_registration_on_pre_registration_staff_requirements FOREIGN KEY (pre_registration_id) REFERENCES pre_registrations (id) on delete cascade on update cascade,
    CONSTRAINT fk_service_on_pre_registration_staff_requirements FOREIGN KEY (staff_id) REFERENCES staff_titles (id) on delete cascade on update cascade
);

