-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Drop the wrongly named table
-- DROP IF EXISTS TABLE level_groups RESTRICT;

-- Create the new table with correct name
CREATE TABLE facility_level_groups
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name         VARCHAR(30),
    code         VARCHAR(30),

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_facility_level_groups PRIMARY KEY (id)
);

ALTER TABLE facility_level_groups
    ADD CONSTRAINT uc_facility_level_groups_uuid UNIQUE (uuid);
