-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.


-----DELETE ME TO APPLY THIS MIGRATION----

CREATE TABLE reviews
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    -- ADD YOUR COLUMNS HERE
    facility_id BIGINT NOT NULL,
    description VARCHAR(255),


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

ALTER TABLE reviews
    ADD CONSTRAINT uc_reviews_uuid UNIQUE (uuid);


ALTER TABLE reviews
   ADD CONSTRAINT FK_reviews_facility
   FOREIGN KEY (facility_id) REFERENCES facilities (id);
