
CREATE TABLE facility_attachments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    attachment_type_id          BIGINT                  NOT NULL,
    user_id                     BIGINT                  NOT NULL,
    application_id              BIGINT                  NOT NULL,
    description                 VARCHAR(255)            NOT NULL,
    is_approved           BOOLEAN,
    is_active           BOOLEAN,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_facility_attachments PRIMARY KEY (id)
);

ALTER TABLE facility_attachments
    ADD CONSTRAINT uc_facility_attachments_uuid UNIQUE (uuid);

ALTER TABLE facility_attachments
    ADD CONSTRAINT FK_facility_attachments_ON_attachment_type FOREIGN KEY (attachment_type_id) REFERENCES attachment_types (id);

ALTER TABLE facility_attachments
    ADD CONSTRAINT FK_facility_attachments_ON_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE facility_attachments
    ADD CONSTRAINT FK_facility_attachments_ON_application FOREIGN KEY (application_id) REFERENCES applications (id);
