-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE equipments
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                  UUID                                    NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    created_by            VARCHAR(255),
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_by            VARCHAR(255),
    is_deleted            BOOLEAN,
    name                  varchar(255)                            not null,
    equipment_category_id bigint                                  not null,
    umdns_code            varchar(255)                            null,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_equipments PRIMARY KEY (id)
);

ALTER TABLE equipments
    ADD CONSTRAINT uc_equipments_uuid UNIQUE (uuid);

alter table equipments
    add constraint equipments_equipment_category_id_fk
        foreign key (equipment_category_id) references equipment_categories
            on update cascade on delete set null;
