-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE license_renewals
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID                                    NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by     VARCHAR(255),
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_by     VARCHAR(255),
    is_deleted     BOOLEAN,
    facility_id    bigint                                  NOT NULL,
    license_number VARCHAR(255)                            NULL,
    date_renewed   TIMESTAMP                               NULL,
    expiry_date    TIMESTAMP                               NULL,
    request_date   TIMESTAMP                               NOT NULL,
    bill_uuid      UUID                                    NULL,
    amount         numeric(32, 2) default 0                null,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_license_renewals PRIMARY KEY (id)
);

ALTER TABLE license_renewals
    ADD CONSTRAINT uc_license_renewals_uuid UNIQUE (uuid);

ALTER TABLE license_renewals
    ADD CONSTRAINT FK_license_renewal_on_facility FOREIGN KEY (facility_id) REFERENCES facilities (id);
