
CREATE TABLE infrastructures
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name                varchar(255)                           not null,
    code                varchar(32)                            not null unique,
    infrastructure_category_id         BIGINT                         NOT NULL,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_infrastructures PRIMARY KEY (id)
);

ALTER TABLE infrastructures
    ADD CONSTRAINT uc_infrastructures_uuid UNIQUE (uuid);

ALTER TABLE infrastructures
    ADD CONSTRAINT FK_infrastructures_ON_infrastructure_category FOREIGN KEY (infrastructure_category_id) REFERENCES infrastructure_categories (id);
