

CREATE TABLE orders
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name                varchar(255) NOT NULL,
    code                varchar(32) NOT NULL unique,
    common_name         varchar(255),
    latitude            FLOAT,
    longitude           FLOAT,
    fbo_denomination    varchar(32),
    official_phone_no   varchar(255) NOT NULL,
    email               varchar(32) NOT NULL unique,
    postal_address      varchar(255) NOT NULL,
    postal_code         varchar(32) NOT NULL,
    website             varchar(32) NOT NULL,
    expected_start_date DATE,
    landmark                            varchar(32),
    nearest_facility_distance_km        INTEGER,
    service_population                  varchar(32),
    catchment_area                      varchar(255) NOT NULL,
    catchment_population                varchar(32),
    operating_status_id                 BIGINT NOT NULL,
    facility_level_id                   BIGINT NOT NULL,
    facility_type_id                    BIGINT NOT NULL,
    ownership_authority_id              BIGINT NOT NULL,
    fund_source_id                      BIGINT NOT NULL,
    admin_hierarchy_id                  BIGINT NOT NULL,
    nearest_facility_id                 BIGINT,
    service_area_location_id            BIGINT NOT NULL,


    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_uuid UNIQUE (uuid);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_ON_adminHierarchy FOREIGN KEY (service_area_location_id) REFERENCES admin_hierarchies (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_ON_operating_status FOREIGN KEY (operating_status_id) REFERENCES facility_operation_statuses (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_ON_facility_level FOREIGN KEY (facility_level_id) REFERENCES facility_levels (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_ON_facility_type FOREIGN KEY (facility_type_id) REFERENCES facility_types (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_ON_ownership_authority FOREIGN KEY (ownership_authority_id) REFERENCES facility_ownership_authorities (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_ON_facility_fund_source FOREIGN KEY (fund_source_id) REFERENCES facility_fund_sources (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_ON_adminHierarchies FOREIGN KEY (admin_hierarchy_id) REFERENCES admin_hierarchies (id);
