-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
-- Enable pgcrypto extension for UUID generation

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create the service_change_requests table
CREATE TABLE service_change_requests (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN DEFAULT FALSE,
    data               JSONB,
    change_request_id  BIGINT,  -- Foreign key column
    CONSTRAINT fk_change_request
        FOREIGN KEY (change_request_id)
        REFERENCES change_requests(id)
        ON DELETE SET NULL  -- Set to NULL if the referenced change_request is deleted
);
