
CREATE TABLE payments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    bill_id                      BIGINT                            NOT NULL,
    amount                            NUMERIC(32,2)                     NOT NULL,
    receipt_number                    VARCHAR(255)                      NOT NULL,
    is_full_amount                    BOOLEAN,
    payment_channel                   VARCHAR(255)                      NOT NULL,
    date_paid                         DATE,
    paid_by                           VARCHAR(255)                      NOT NULL,
    sp_code                           VARCHAR(255)                      NOT NULL,
    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_uuid UNIQUE (uuid);

ALTER TABLE payments
    ADD CONSTRAINT FK_payments_ON_bill FOREIGN KEY (bill_id) REFERENCES bills (id);
