-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
--
--

CREATE TABLE equipment_change_requests
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    facility_id                             BIGINT                       NOT NULL,
    equipment_id                            BIGINT                       NOT NULL,
    change_request_id                       BIGINT                       NOT NULL,
    type VARCHAR(255),
    quantity            float                                   NOT NULL DEFAULT 0.0,

    CONSTRAINT pk_equipment_change_requests PRIMARY KEY (id)
);

ALTER TABLE equipment_change_requests
    ADD CONSTRAINT uc_equipment_change_requests_uuid UNIQUE (uuid);

ALTER TABLE equipment_change_requests
    ADD CONSTRAINT FK_equipment_change_requests_ON_facility FOREIGN KEY (facility_id) REFERENCES facilities (id);

ALTER TABLE equipment_change_requests
    ADD CONSTRAINT FK_equipment_change_requests_ON_equipment FOREIGN KEY (equipment_id) REFERENCES equipments (id);

ALTER TABLE equipment_change_requests
    ADD CONSTRAINT FK_equipment_change_requests_ON_change_request FOREIGN KEY (change_request_id) REFERENCES change_requests (id);
