-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.


-----DELETE ME TO APPLY THIS MIGRATION----

CREATE TABLE api_keys
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    -- ADD YOUR COLUMNS HERE
    system_name        VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    expiry_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    api_key            VARCHAR(255)                            NOT NULL,
    status             VARCHAR(50)                             DEFAULT 'ACTIVE' NOT NULL,
    code               VARCHAR(50)                             NOT NULL,
    contact_email      VARCHAR(255),
    is_approved        BOOLEAN DEFAULT FALSE,
    -- ADD YOUR COLUMNS HERE

    CONSTRAINT pk_api_keys PRIMARY KEY (id)
);

ALTER TABLE api_keys
    ADD CONSTRAINT uc_api_keys_uuid UNIQUE (uuid);
