
CREATE TABLE application_types
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name               VARCHAR(255)                            NOT NULL,
    code               VARCHAR(255)                            NOT NULL UNIQUE,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_application_types PRIMARY KEY (id)
);

ALTER TABLE application_types
    ADD CONSTRAINT uc_application_types_uuid UNIQUE (uuid);
