
CREATE TABLE notifications
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    notification_type_id    BIGINT                             NOT NULL,
    recipient_id       BIGINT                                  NOT NULL,
    title              VARCHAR(70),
    message            VARCHAR(255),
    is_read            BOOLEAN,
    sent_at            DATE,
    read_at            DATE,
    is_active          BOOLEAN,

    -- ADD YOUR COLUMNS HERE


    -- ADD YOUR COLUMNS HERE
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

ALTER TABLE notifications
    ADD CONSTRAINT uc_notifications_uuid UNIQUE (uuid);

ALTER TABLE notifications
    ADD CONSTRAINT FK_notifications_ON_user FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_notifications_ON_notification_type FOREIGN KEY (notification_type_id) REFERENCES notification_types (id);
