-- Step 1: Create bed_types table
CREATE TABLE IF NOT EXISTS bed_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_by  VARCHAR(255),
    is_deleted  BOOLEAN DEFAULT FALSE,
    version     BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    CONSTRAINT pk_bed_types PRIMARY KEY (id),
    CONSTRAINT uc_bed_types_uuid UNIQUE (uuid)
);

-- Step 2: Add bed_type_id to room_types
ALTER TABLE room_types
    ADD COLUMN IF NOT EXISTS bed_type_id BIGINT;

ALTER TABLE room_types
    ADD CONSTRAINT fk_room_types_bed_type_id
        FOREIGN KEY (bed_type_id)
            REFERENCES bed_types (id);

-- Step 3: Seed bed_types table
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM bed_types WHERE name = 'KING') THEN
            INSERT INTO bed_types (uuid, created_at, updated_at, is_deleted, version, name, description)
            VALUES (gen_random_uuid(), NOW(), NOW(), FALSE, 1, 'KING',
                    'A spacious king-size bed, ideal for couples or guests who prefer extra room.'),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 1, 'QUEEN',
                    'A comfortable queen-size bed, perfect for solo travelers or couples.'),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 1, 'TWIN',
                    'Two separate twin beds, great for sharing without compromising personal space.'),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 1, 'DOUBLE',
                    'A standard double bed suitable for single or double occupancy.'),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 1, 'SINGLE',
                    'A single bed ideal for one person, commonly found in budget or child-friendly rooms.'),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 1, 'BUNK BEDS',
                    'Stacked twin beds, perfect for kids or shared accommodations in hostels or family suites.'),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 1, 'SOFA BED',
                    'A sofa that folds out into a bed, useful in multi-purpose or compact spaces.'),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 1, 'MURPHY BED',
                    'A wall-mounted bed that folds away when not in use, ideal for maximizing space in smaller rooms.');
        END IF;
    END
$$;

-- Step 4: Update room_types to set bed_type_id based on string match
UPDATE room_types rt
SET bed_type_id = bt.id
FROM bed_types bt
WHERE UPPER(rt.bed_type) = bt.name
  AND rt.bed_type_id IS NULL;

-- Step 5: Make bed_type_id non-nullable
ALTER TABLE room_types
    ALTER COLUMN bed_type_id SET NOT NULL;

-- Step 6: Drop old string column
ALTER TABLE room_types
    DROP COLUMN IF EXISTS bed_type;
