-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Create assessment_requests table
CREATE TABLE assessment_requests
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                    UUID                                    NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    created_by              VARCHAR(255),
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_by              VARCHAR(255),
    is_deleted              BOOLEAN,

    -- Assessment request specific columns
    hotel_id                BIGINT                                  NOT NULL,
    contact_person          VARCHAR(255)                            NOT NULL,
    email                   VARCHAR(255)                            NOT NULL,
    phone_number            VARCHAR(20)                             NOT NULL,
    address                 TEXT,
    requested_date          DATE,
    additional_comments     TEXT,
    terms_accepted          BOOLEAN                                 NOT NULL DEFAULT FALSE,
    status                  VARCHAR(50)                             NOT NULL DEFAULT 'PENDING',
    submitted_at            TIMESTAMP WITHOUT TIME ZONE,
    processed_at            TIMESTAMP WITHOUT TIME ZONE,
    review_started_at       TIMESTAMP WITHOUT TIME ZONE,
    processed_by            BIGINT,
    processing_notes        TEXT,
    submitted_by            BIGINT,

    CONSTRAINT pk_assessment_requests PRIMARY KEY (id)
);

-- Create essential_items table
CREATE TABLE essential_items
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                    UUID                                    NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    created_by              VARCHAR(255),
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_by              VARCHAR(255),
    is_deleted              BOOLEAN,

    -- Essential item specific columns
    assessment_request_id   BIGINT                                  NOT NULL,
    item_number             INTEGER                                 NOT NULL,
    item_description        TEXT                                    NOT NULL,
    compliance_requirement  TEXT,
    compliance              VARCHAR(50),
    evidence_provided       BOOLEAN                                 NOT NULL DEFAULT FALSE,
    evidence_description    TEXT,
    comments                TEXT,
    evidence_type           VARCHAR(100),

    CONSTRAINT pk_essential_items PRIMARY KEY (id)
);

-- Create essential_item_evidence table
CREATE TABLE essential_item_evidence
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                    UUID                                    NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    created_by              VARCHAR(255),
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_by              VARCHAR(255),
    is_deleted              BOOLEAN,

    -- Evidence specific columns
    essential_item_id       BIGINT                                  NOT NULL,
    evidence_description    VARCHAR(500),
    evidence_type           VARCHAR(100),
    file_url                TEXT,
    file_name               VARCHAR(255),
    file_size               BIGINT,
    mime_type               VARCHAR(100),
    file_upload_id          BIGINT,

    CONSTRAINT pk_essential_item_evidence PRIMARY KEY (id)
);

-- Add unique constraints
ALTER TABLE assessment_requests ADD CONSTRAINT uc_assessment_requests_uuid UNIQUE (uuid);
ALTER TABLE essential_items ADD CONSTRAINT uc_essential_items_uuid UNIQUE (uuid);
ALTER TABLE essential_item_evidence ADD CONSTRAINT uc_essential_item_evidence_uuid UNIQUE (uuid);

-- Add foreign key constraints
ALTER TABLE assessment_requests ADD CONSTRAINT fk_assessment_request_hotel 
    FOREIGN KEY (hotel_id) REFERENCES hotels(id);

ALTER TABLE assessment_requests ADD CONSTRAINT fk_assessment_request_user 
    FOREIGN KEY (submitted_by) REFERENCES users(id);

ALTER TABLE essential_items ADD CONSTRAINT fk_essential_item_assessment_request 
    FOREIGN KEY (assessment_request_id) REFERENCES assessment_requests(id) ON DELETE CASCADE;

ALTER TABLE essential_item_evidence ADD CONSTRAINT fk_essential_item_evidence_essential_item 
    FOREIGN KEY (essential_item_id) REFERENCES essential_items(id) ON DELETE CASCADE;

ALTER TABLE essential_item_evidence ADD CONSTRAINT fk_essential_item_evidence_file_upload 
    FOREIGN KEY (file_upload_id) REFERENCES file_uploads(id);

-- Add check constraints for enum values
ALTER TABLE assessment_requests ADD CONSTRAINT chk_assessment_request_status 
    CHECK (status IN ('PENDING', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED'));

ALTER TABLE essential_items ADD CONSTRAINT chk_essential_item_compliance 
    CHECK (compliance IS NULL OR compliance IN ('compliant', 'non-compliant', 'partially-compliant'));

-- Add unique constraint for item number within assessment request
ALTER TABLE essential_items ADD CONSTRAINT uc_essential_items_assessment_request_item_number 
    UNIQUE (assessment_request_id, item_number);

-- Create indexes for better performance
CREATE INDEX idx_assessment_requests_hotel_id ON assessment_requests(hotel_id);
CREATE INDEX idx_assessment_requests_submitted_by ON assessment_requests(submitted_by);
CREATE INDEX idx_assessment_requests_status ON assessment_requests(status);
CREATE INDEX idx_assessment_requests_submitted_at ON assessment_requests(submitted_at);
CREATE INDEX idx_assessment_requests_email ON assessment_requests(email);

CREATE INDEX idx_essential_items_assessment_request_id ON essential_items(assessment_request_id);
CREATE INDEX idx_essential_items_item_number ON essential_items(item_number);
CREATE INDEX idx_essential_items_compliance ON essential_items(compliance);

CREATE INDEX idx_essential_item_evidence_essential_item_id ON essential_item_evidence(essential_item_id);
CREATE INDEX idx_essential_item_evidence_file_upload_id ON essential_item_evidence(file_upload_id);

-- Add comments for documentation
COMMENT ON TABLE assessment_requests IS 'Stores assessment requests submitted by hotels for compliance evaluation';
COMMENT ON TABLE essential_items IS 'Stores individual compliance items that are part of an assessment request';
COMMENT ON TABLE essential_item_evidence IS 'Stores evidence files uploaded for essential items';

COMMENT ON COLUMN assessment_requests.status IS 'Status of the assessment request: PENDING, SUBMITTED, UNDER_REVIEW, APPROVED, REJECTED';
COMMENT ON COLUMN essential_items.compliance IS 'Compliance status: compliant, non-compliant, partially-compliant';
COMMENT ON COLUMN essential_items.item_number IS 'Sequential number of the essential item within the assessment';
COMMENT ON COLUMN essential_item_evidence.evidence_type IS 'Type of evidence provided (document, image, video, etc.)';