-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Create self_assessments table for facility owner self-assessments
CREATE TABLE self_assessments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    hotel_id           BIGINT                                  NOT NULL,
    form_id            BIGINT                                  NOT NULL,
    submitted_by       VARCHAR(255)                            NOT NULL,
    submitted_at       TIMESTAMP WITHOUT TIME ZONE,
    total_score        DOUBLE PRECISION,
    max_possible_score DOUBLE PRECISION,
    percentage         DOUBLE PRECISION,
    estimated_rating   VARCHAR(100),
    status             VARCHAR(50)                             NOT NULL DEFAULT 'DRAFT',
    is_official        BOOLEAN                                 NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN                                 DEFAULT FALSE,
    CONSTRAINT pk_self_assessments PRIMARY KEY (id)
);

ALTER TABLE self_assessments
    ADD CONSTRAINT uc_self_assessments_uuid UNIQUE (uuid);

ALTER TABLE self_assessments
    ADD CONSTRAINT fk_self_assessments_hotel FOREIGN KEY (hotel_id) REFERENCES hotels (id);

ALTER TABLE self_assessments
    ADD CONSTRAINT fk_self_assessments_form FOREIGN KEY (form_id) REFERENCES forms (id);

CREATE INDEX idx_self_assessments_hotel ON self_assessments(hotel_id);
CREATE INDEX idx_self_assessments_status ON self_assessments(status);
CREATE INDEX idx_self_assessments_is_official ON self_assessments(is_official);

-- Create self_assessment_scores table for section-level scores
CREATE TABLE self_assessment_scores
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    self_assessment_id BIGINT                                  NOT NULL,
    section_id         BIGINT                                  NOT NULL,
    score              DOUBLE PRECISION,
    max_possible       DOUBLE PRECISION,
    percentage         DOUBLE PRECISION,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN                                 DEFAULT FALSE,
    CONSTRAINT pk_self_assessment_scores PRIMARY KEY (id)
);

ALTER TABLE self_assessment_scores
    ADD CONSTRAINT uc_self_assessment_scores_uuid UNIQUE (uuid);

ALTER TABLE self_assessment_scores
    ADD CONSTRAINT fk_self_assessment_scores_assessment FOREIGN KEY (self_assessment_id) REFERENCES self_assessments (id) ON DELETE CASCADE;

ALTER TABLE self_assessment_scores
    ADD CONSTRAINT fk_self_assessment_scores_section FOREIGN KEY (section_id) REFERENCES form_sections (id);

CREATE INDEX idx_self_assessment_scores_assessment ON self_assessment_scores(self_assessment_id);
CREATE INDEX idx_self_assessment_scores_section ON self_assessment_scores(section_id);

-- Create self_assessment_field_responses table for field-level responses
CREATE TABLE self_assessment_field_responses
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    self_assessment_id BIGINT                                  NOT NULL,
    field_id           BIGINT                                  NOT NULL,
    value              TEXT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN                                 DEFAULT FALSE,
    CONSTRAINT pk_self_assessment_field_responses PRIMARY KEY (id)
);

ALTER TABLE self_assessment_field_responses
    ADD CONSTRAINT uc_self_assessment_field_responses_uuid UNIQUE (uuid);

ALTER TABLE self_assessment_field_responses
    ADD CONSTRAINT fk_self_assessment_field_responses_assessment FOREIGN KEY (self_assessment_id) REFERENCES self_assessments (id) ON DELETE CASCADE;

ALTER TABLE self_assessment_field_responses
    ADD CONSTRAINT fk_self_assessment_field_responses_field FOREIGN KEY (field_id) REFERENCES form_fields (id);

CREATE INDEX idx_self_assessment_field_responses_assessment ON self_assessment_field_responses(self_assessment_id);
CREATE INDEX idx_self_assessment_field_responses_field ON self_assessment_field_responses(field_id);
