-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Create hotel_assessment_approvals table for Director of Tourism approval workflow
CREATE TABLE hotel_assessment_approvals
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                            UUID                                    NOT NULL,
    created_at                      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    created_by                      VARCHAR(255),
    updated_at                      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_by                      VARCHAR(255),
    is_deleted                      BOOLEAN DEFAULT FALSE,

    -- References
    hotel_id                        BIGINT                                  NOT NULL,
    form_id                         BIGINT                                  NOT NULL,

    -- Form submission references (3 assessors)
    submission_1_id                 BIGINT,
    submission_2_id                 BIGINT,
    submission_3_id                 BIGINT,

    -- Calculated final scores (average of 3 submissions)
    final_total_score               NUMERIC(10, 2),
    final_max_score                 NUMERIC(10, 2),
    final_percentage                NUMERIC(5, 2),
    final_rating                    VARCHAR(50),

    -- Variance status
    has_unresolved_variances        BOOLEAN DEFAULT FALSE,
    variance_resolution_count       INTEGER DEFAULT 0,
    all_variances_resolved_at       TIMESTAMP WITHOUT TIME ZONE,

    -- DT Approval workflow
    status                          VARCHAR(50) NOT NULL DEFAULT 'PENDING_VARIANCE_RESOLUTION',
    submitted_to_dt_at              TIMESTAMP WITHOUT TIME ZONE,
    approved_by_dt_id               BIGINT,
    dt_approval_date                TIMESTAMP WITHOUT TIME ZONE,
    dt_rejection_reason             TEXT,
    dt_comments                     TEXT,

    CONSTRAINT pk_hotel_assessment_approvals PRIMARY KEY (id)
);

-- Add unique constraints
ALTER TABLE hotel_assessment_approvals
    ADD CONSTRAINT uc_hotel_assessment_approvals_uuid UNIQUE (uuid);

ALTER TABLE hotel_assessment_approvals
    ADD CONSTRAINT uc_hotel_assessment_approvals_hotel_form UNIQUE (hotel_id, form_id);

-- Add foreign key constraints
ALTER TABLE hotel_assessment_approvals
    ADD CONSTRAINT fk_hotel_assessment_approvals_hotel FOREIGN KEY (hotel_id)
    REFERENCES hotels (id);

ALTER TABLE hotel_assessment_approvals
    ADD CONSTRAINT fk_hotel_assessment_approvals_form FOREIGN KEY (form_id)
    REFERENCES forms (id);

ALTER TABLE hotel_assessment_approvals
    ADD CONSTRAINT fk_hotel_assessment_approvals_submission_1 FOREIGN KEY (submission_1_id)
    REFERENCES form_submissions (id);

ALTER TABLE hotel_assessment_approvals
    ADD CONSTRAINT fk_hotel_assessment_approvals_submission_2 FOREIGN KEY (submission_2_id)
    REFERENCES form_submissions (id);

ALTER TABLE hotel_assessment_approvals
    ADD CONSTRAINT fk_hotel_assessment_approvals_submission_3 FOREIGN KEY (submission_3_id)
    REFERENCES form_submissions (id);

ALTER TABLE hotel_assessment_approvals
    ADD CONSTRAINT fk_hotel_assessment_approvals_approved_by FOREIGN KEY (approved_by_dt_id)
    REFERENCES users (id);

-- Create indexes for performance
CREATE INDEX idx_approval_status ON hotel_assessment_approvals(status);
CREATE INDEX idx_approval_hotel ON hotel_assessment_approvals(hotel_id);
CREATE INDEX idx_approval_has_variances ON hotel_assessment_approvals(has_unresolved_variances);
CREATE INDEX idx_approval_submitted_dt ON hotel_assessment_approvals(submitted_to_dt_at);

-- Add comments
COMMENT ON TABLE hotel_assessment_approvals IS 'Tracks Director of Tourism approval workflow for hotel assessments';
COMMENT ON COLUMN hotel_assessment_approvals.status IS 'Status: PENDING_VARIANCE_RESOLUTION, READY_FOR_APPROVAL, APPROVED, REJECTED, REVISION_REQUIRED';
COMMENT ON COLUMN hotel_assessment_approvals.final_rating IS 'Final star rating: 5-STAR, 4-STAR, 3-STAR, 2-STAR, 1-STAR';
COMMENT ON COLUMN hotel_assessment_approvals.has_unresolved_variances IS 'Blocks DT approval until all variances resolved';
COMMENT ON COLUMN hotel_assessment_approvals.variance_resolution_count IS 'Number of times assessors have re-submitted to resolve variances';
