-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Create assessor_variance_notifications table to notify assessors of score variances
CREATE TABLE assessor_variance_notifications
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                          UUID                                    NOT NULL,
    created_at                    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    created_by                    VARCHAR(255),
    updated_at                    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_by                    VARCHAR(255),
    is_deleted                    BOOLEAN DEFAULT FALSE,

    -- References
    assessment_variance_log_id    BIGINT                                  NOT NULL,
    assessor_id                   BIGINT                                  NOT NULL,

    -- Notification details
    notification_type             VARCHAR(50)                             NOT NULL,
    message                       TEXT,
    is_read                       BOOLEAN DEFAULT FALSE,
    read_at                       TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_assessor_variance_notifications PRIMARY KEY (id)
);

-- Add unique constraint
ALTER TABLE assessor_variance_notifications
    ADD CONSTRAINT uc_assessor_variance_notifications_uuid UNIQUE (uuid);

-- Add foreign key constraints
ALTER TABLE assessor_variance_notifications
    ADD CONSTRAINT fk_assessor_variance_notifications_variance_log FOREIGN KEY (assessment_variance_log_id)
    REFERENCES assessment_variance_logs (id) ON DELETE CASCADE;

ALTER TABLE assessor_variance_notifications
    ADD CONSTRAINT fk_assessor_variance_notifications_assessor FOREIGN KEY (assessor_id)
    REFERENCES assessors (id);

-- Create indexes for performance
CREATE INDEX idx_variance_notifications_assessor ON assessor_variance_notifications(assessor_id, is_read);
CREATE INDEX idx_variance_notifications_log ON assessor_variance_notifications(assessment_variance_log_id);
CREATE INDEX idx_variance_notifications_created_at ON assessor_variance_notifications(created_at DESC);

-- Add comments
COMMENT ON TABLE assessor_variance_notifications IS 'Notifications sent to assessors when score variances are detected';
COMMENT ON COLUMN assessor_variance_notifications.notification_type IS 'Type: SCORE_TOO_HIGH, SCORE_TOO_LOW, VARIANCE_RESOLVED, etc.';
COMMENT ON COLUMN assessor_variance_notifications.is_read IS 'Whether the assessor has read this notification';
COMMENT ON COLUMN assessor_variance_notifications.message IS 'Human-readable notification message';
