-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
-- Migration script to add scoring and subsection support

-- Add scoring columns to form_sections
ALTER TABLE form_sections
ADD COLUMN weight DOUBLE PRECISION,
ADD COLUMN max_score INTEGER,
ADD COLUMN section_level INTEGER DEFAULT 0,
ADD COLUMN parent_section_id BIGINT,
ADD CONSTRAINT fk_section_parent FOREIGN KEY (parent_section_id) REFERENCES form_sections(id);

-- Add index for parent_section_id
CREATE INDEX idx_section_parent ON form_sections(parent_section_id);

-- Add scoring columns to form_field_options
ALTER TABLE form_field_options
ADD COLUMN score INTEGER;


-- Create form_submission_scores table
CREATE TABLE form_submission_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    is_deleted BOOLEAN DEFAULT FALSE,
    submission_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    score DOUBLE PRECISION,
    max_possible DOUBLE PRECISION,
    percentage DOUBLE PRECISION,
    CONSTRAINT pk_form_submission_scores PRIMARY KEY (id),
    CONSTRAINT uc_form_submission_scores_uuid UNIQUE (uuid),
    CONSTRAINT fk_scores_submission FOREIGN KEY (submission_id) REFERENCES form_submissions(id),
    CONSTRAINT fk_scores_section FOREIGN KEY (section_id) REFERENCES form_sections(id)
);

-- Add indexes for form_submission_scores
CREATE INDEX idx_submission_scores_submission ON form_submission_scores(submission_id);
CREATE INDEX idx_submission_scores_section ON form_submission_scores(section_id);

-- Add scoring columns to form_submissions
ALTER TABLE form_submissions
ADD COLUMN total_score DOUBLE PRECISION,
ADD COLUMN max_possible_score DOUBLE PRECISION,
ADD COLUMN percentage_score DOUBLE PRECISION;

-- Fix column name if needed (ensure field_type is used instead of fieldType)
-- Check if the column exists with the old name before running this part
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'form_fields' AND column_name = 'fieldtype') THEN
        ALTER TABLE form_fields RENAME COLUMN fieldtype TO field_type;
    END IF;
END
$$;

-- Update any existing data to give default values
UPDATE form_sections SET weight = 1.0 WHERE weight IS NULL;
UPDATE form_sections SET section_level = 0 WHERE section_level IS NULL;
UPDATE form_fields SET validation_rules = '{}' WHERE validation_rules IS NULL;


-- Create form_submission_drafts table
CREATE TABLE form_submission_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    is_deleted BOOLEAN DEFAULT FALSE,
    submitted_by VARCHAR(255) NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    form_id BIGINT,
    current_section_index INTEGER,
    form_data TEXT,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_form_submission_drafts_form FOREIGN KEY (form_id) REFERENCES forms(id)
);

-- Add a comment to facilitate finding this migration in the future
COMMENT ON TABLE form_submission_scores IS 'Added in scoring system migration';
