-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE assessor_establishment_types
(
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uuid        uuid         NOT NULL,
    created_at  timestamp without time zone,
    created_by  character varying(255),
    updated_at  timestamp without time zone,
    updated_by  character varying(255),
    is_deleted  boolean,
    assessor_id bigint       not null,
    preference  VARCHAR(255) not null,
    CONSTRAINT fk_assessor_id_on_assessor_establishment_types FOREIGN KEY (assessor_id) REFERENCES assessors (id)
);
