-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Create new contact_persons table
CREATE TABLE contact_persons (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL,
    created_at timestamp without time zone,
    created_by character varying(255),
    updated_at timestamp without time zone,
    updated_by character varying(255),
    is_deleted boolean,
    name character varying(255) NOT NULL,
    address character varying(255),
    email character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    physical_address character varying(255),
    fax character varying(255),
    is_primary boolean NOT NULL DEFAULT true,
    company_id bigint NOT NULL,
    CONSTRAINT pk_contact_persons PRIMARY KEY (id),
    CONSTRAINT uc_contact_persons_uuid UNIQUE (uuid),
    CONSTRAINT fk_contact_persons_on_company FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- Create index on company_id for better query performance
CREATE INDEX idx_contact_persons_company_id ON contact_persons(company_id);
