-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Forms table - Stores form definitions
CREATE TABLE forms
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name               VARCHAR(255)                            NOT NULL,
    description        TEXT,
    CONSTRAINT pk_forms PRIMARY KEY (id)
);
ALTER TABLE forms
    ADD CONSTRAINT uc_forms_uuid UNIQUE (uuid);

-- Form Sections table - Stores sections within forms
CREATE TABLE form_sections
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    title              VARCHAR(255)                            NOT NULL,
    order_index        INTEGER                                 NOT NULL,
    form_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_form_sections PRIMARY KEY (id),
    CONSTRAINT fk_form_sections_forms FOREIGN KEY (form_id) REFERENCES forms (id)
);
ALTER TABLE form_sections
    ADD CONSTRAINT uc_form_sections_uuid UNIQUE (uuid);

-- Form Fields table - Stores fields within sections
CREATE TABLE form_fields
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    label              VARCHAR(255)                            NOT NULL,
    field_type         VARCHAR(50)                             NOT NULL,
    required           BOOLEAN                                 NOT NULL DEFAULT FALSE,
    placeholder        VARCHAR(255),
    help_text          VARCHAR(255),
    order_index        INTEGER                                 NOT NULL,
    validation_rules   TEXT,
    section_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_form_fields PRIMARY KEY (id),
    CONSTRAINT fk_form_fields_sections FOREIGN KEY (section_id) REFERENCES form_sections (id)
);
ALTER TABLE form_fields
    ADD CONSTRAINT uc_form_fields_uuid UNIQUE (uuid);

-- Form Field Options table - Stores options for select, radio, checkbox fields
CREATE TABLE form_field_options
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    label              VARCHAR(255)                            NOT NULL,
    value              VARCHAR(255)                            NOT NULL,
    order_index        INTEGER                                 NOT NULL,
    field_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_form_field_options PRIMARY KEY (id),
    CONSTRAINT fk_form_field_options_fields FOREIGN KEY (field_id) REFERENCES form_fields (id)
);
ALTER TABLE form_field_options
    ADD CONSTRAINT uc_form_field_options_uuid UNIQUE (uuid);

-- Form Submissions table - Stores form submission metadata
CREATE TABLE form_submissions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    form_id            BIGINT                                  NOT NULL,
    submitted_by       VARCHAR(255),
    submitted_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_form_submissions PRIMARY KEY (id),
    CONSTRAINT fk_form_submissions_forms FOREIGN KEY (form_id) REFERENCES forms (id)
);
ALTER TABLE form_submissions
    ADD CONSTRAINT uc_form_submissions_uuid UNIQUE (uuid);

-- Form Field Responses table - Stores individual field responses within a submission
CREATE TABLE form_field_responses
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    submission_id      BIGINT                                  NOT NULL,
    field_id           BIGINT                                  NOT NULL,
    value              TEXT,
    CONSTRAINT pk_form_field_responses PRIMARY KEY (id),
    CONSTRAINT fk_form_field_responses_submissions FOREIGN KEY (submission_id) REFERENCES form_submissions (id),
    CONSTRAINT fk_form_field_responses_fields FOREIGN KEY (field_id) REFERENCES form_fields (id)
);
ALTER TABLE form_field_responses
    ADD CONSTRAINT uc_form_field_responses_uuid UNIQUE (uuid);

-- Create indexes for better performance
CREATE INDEX idx_form_sections_form_id ON form_sections(form_id);
CREATE INDEX idx_form_fields_section_id ON form_fields(section_id);
CREATE INDEX idx_form_field_options_field_id ON form_field_options(field_id);
CREATE INDEX idx_form_submissions_form_id ON form_submissions(form_id);
CREATE INDEX idx_form_field_responses_submission_id ON form_field_responses(submission_id);
CREATE INDEX idx_form_field_responses_field_id ON form_field_responses(field_id);
