-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Create system_configuration table for configurable settings
CREATE TABLE system_configurations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN DEFAULT FALSE,
    config_key         VARCHAR(100)                            NOT NULL,
    config_value       TEXT                                    NOT NULL,
    config_type        VARCHAR(50)                             NOT NULL,
    description        TEXT,
    category           VARCHAR(50),
    is_editable        BOOLEAN DEFAULT TRUE,
    CONSTRAINT pk_system_configurations PRIMARY KEY (id)
);

-- Add unique constraints
ALTER TABLE system_configurations
    ADD CONSTRAINT uc_system_configurations_uuid UNIQUE (uuid);
ALTER TABLE system_configurations
    ADD CONSTRAINT uc_system_configurations_config_key UNIQUE (config_key);

-- Create indexes for fast lookups
CREATE INDEX idx_system_config_category ON system_configurations(category);
CREATE INDEX idx_system_config_key ON system_configurations(config_key);

-- Insert default variance threshold configuration
INSERT INTO system_configurations (uuid, config_key, config_value, config_type, description, category, is_editable, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'VARIANCE_THRESHOLD_POINTS', '5.0', 'DECIMAL', 'Score difference threshold (in points) that triggers variance alert between assessors', 'ASSESSMENT', TRUE, NOW(), NOW()),
    (gen_random_uuid(), 'VARIANCE_CHECK_ENABLED', 'true', 'BOOLEAN', 'Enable or disable variance checking across assessor submissions', 'ASSESSMENT', TRUE, NOW(), NOW()),
    (gen_random_uuid(), 'VARIANCE_COMPARISON_METHOD', 'PAIRWISE', 'STRING', 'Method for comparing scores: PAIRWISE, RANGE, or AVERAGE', 'ASSESSMENT', TRUE, NOW(), NOW()),
    (gen_random_uuid(), 'DT_APPROVAL_REQUIRED', 'true', 'BOOLEAN', 'Require Director of Tourism approval after variance resolution', 'ASSESSMENT', TRUE, NOW(), NOW()),
    (gen_random_uuid(), 'VARIANCE_NOTIFICATION_EMAIL_ENABLED', 'true', 'BOOLEAN', 'Send email notifications when variances are detected', 'NOTIFICATION', TRUE, NOW(), NOW());

-- Add comments to table
COMMENT ON TABLE system_configurations IS 'System-wide configuration settings that can be modified through admin UI';
COMMENT ON COLUMN system_configurations.config_key IS 'Unique identifier for the configuration setting';
COMMENT ON COLUMN system_configurations.config_type IS 'Data type of the config value for proper parsing (INTEGER, DECIMAL, STRING, BOOLEAN, JSON)';
COMMENT ON COLUMN system_configurations.is_editable IS 'Whether this setting can be modified via UI (false for system-critical settings)';
