-- Step 1: Create bed_room_types table
CREATE TABLE IF NOT EXISTS bed_room_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_by  VARCHAR(255),
    is_deleted  BOOLEAN DEFAULT FALSE,
    code        VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    CONSTRAINT pk_bed_room_types PRIMARY KEY (id),
    CONSTRAINT uc_bed_room_types_uuid UNIQUE (uuid)
);


-- Step 2: Seed bed_room_types table
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM bed_room_types WHERE name = 'KING') THEN
            INSERT INTO bed_room_types (uuid, created_at, updated_at, is_deleted, code, name, description)
            VALUES (gen_random_uuid(), NOW(), NOW(), FALSE, 'SR_1', 'Standard Room (Single Bed)',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'SR_2', 'Standard Room (Twin Bed)',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'SR_3', 'Standard Room (Triple Bed)',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'EX', 'Executive',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'PS', 'Presidential Suite',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'ST', 'Suite',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'COT', 'Cottage',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'FA', 'Family Suite',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'SR', 'Standard Room (Double)',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'TC', 'Tented Camp',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'TS', 'Tented Suite',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'TR', 'Tented Room',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'FT', 'Family Tent',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'VL', 'Villa',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'SD', 'Super Deluxe',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'SDT', 'Super Deluxe (Twin Beds)',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'SDP', 'Super Deluxe (Tripple Beds)',''),
                   (gen_random_uuid(), NOW(), NOW(), FALSE, 'DL', 'Deluxe Room','');
        END IF;
    END
$$;
