-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
CREATE TABLE password_reset_tokens
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid    UUID NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    token       VARCHAR(255)  NOT NULL,
    user_id      BIGINT,
    expiry_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),

    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);
ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_uuid UNIQUE (uuid);
