-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

CREATE TABLE hotels
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    -- Hotel specific columns
    version            BIGINT                                  NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    website            VARCHAR(255),
    email              VARCHAR(255)                            NOT NULL,
    phone              VARCHAR(255)                            NOT NULL,
    latitude           DOUBLE PRECISION,
    longitude          DOUBLE PRECISION,
    property_type      VARCHAR(50),
    default_image_id   BIGINT,
    status             VARCHAR(50),
    is_active          BOOLEAN                                 NOT NULL,
    company_id         BIGINT,
    location_id        BIGINT,

    CONSTRAINT pk_hotels PRIMARY KEY (id)
);

-- Create room_types table
CREATE TABLE room_types
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    version            BIGINT                                  NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    description        TEXT,
    quantity           INTEGER                                 NOT NULL,
    size               DOUBLE PRECISION,
    max_occupancy      INTEGER,
    bed_type           VARCHAR(255),
    hotel_id           BIGINT                                  NOT NULL,

    CONSTRAINT pk_room_types PRIMARY KEY (id)
);

-- Create room_amenities table
CREATE TABLE room_amenities
(
    room_type_id       BIGINT                                  NOT NULL,
    amenity            VARCHAR(255)                            NOT NULL
);

-- Create hotel_facilities table
CREATE TABLE hotel_facilities
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    version            BIGINT                                  NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    facility_type      VARCHAR(50),
    description        TEXT,
    capacity           INTEGER,
    opening_hours      VARCHAR(255),
    hotel_id           BIGINT                                  NOT NULL,

    CONSTRAINT pk_hotel_facilities PRIMARY KEY (id)
);

-- Create hotel_media table
CREATE TABLE hotel_media
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,

    description        VARCHAR(255)                            NOT NULL,
    is_approved        BOOLEAN                                 NOT NULL,
    media_id           BIGINT,
    hotel_id           BIGINT                                  NOT NULL,
    user_id            BIGINT,
    is_default         BOOLEAN                                 NOT NULL,

    CONSTRAINT pk_hotel_media PRIMARY KEY (id)
);

-- Add constraints and indexes
ALTER TABLE hotels ADD CONSTRAINT uc_hotels_uuid UNIQUE (uuid);
ALTER TABLE room_types ADD CONSTRAINT uc_room_types_uuid UNIQUE (uuid);
ALTER TABLE hotel_facilities ADD CONSTRAINT uc_hotel_facilities_uuid UNIQUE (uuid);
ALTER TABLE hotel_media ADD CONSTRAINT uc_hotel_media_uuid UNIQUE (uuid);

-- Add foreign key constraints
ALTER TABLE hotels ADD CONSTRAINT fk_hotels_on_company FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE hotels ADD CONSTRAINT fk_hotels_on_location FOREIGN KEY (location_id) REFERENCES admin_hierarchies(id);
ALTER TABLE hotels ADD CONSTRAINT fk_hotels_on_default_image FOREIGN KEY (default_image_id) REFERENCES hotel_media(id);

ALTER TABLE room_types ADD CONSTRAINT fk_room_types_on_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(id);

ALTER TABLE hotel_facilities ADD CONSTRAINT fk_hotel_facilities_on_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(id);

ALTER TABLE hotel_media ADD CONSTRAINT fk_hotel_media_on_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(id);
ALTER TABLE hotel_media ADD CONSTRAINT fk_hotel_media_on_file_upload FOREIGN KEY (media_id) REFERENCES file_uploads(id);
ALTER TABLE hotel_media ADD CONSTRAINT fk_hotel_media_on_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE room_amenities ADD CONSTRAINT fk_room_amenities_on_room_type FOREIGN KEY (room_type_id) REFERENCES room_types(id);

-- Create indexes for better performance
CREATE INDEX idx_hotels_company_id ON hotels(company_id);
CREATE INDEX idx_hotels_location_id ON hotels(location_id);
CREATE INDEX idx_room_types_hotel_id ON room_types(hotel_id);
CREATE INDEX idx_hotel_facilities_hotel_id ON hotel_facilities(hotel_id);
CREATE INDEX idx_hotel_media_hotel_id ON hotel_media(hotel_id);
CREATE INDEX idx_hotel_media_media_id ON hotel_media(media_id);
CREATE INDEX idx_hotel_media_user_id ON hotel_media(user_id);
