-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
-----DELETE ME TO APPLY THIS MIGRATION----

CREATE TABLE incident_reports
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    incident_type_id INTEGER                                 NOT NULL,
    visitor_id      INTEGER                                 NOT NULL,
    hotel_id        INTEGER                                 NOT NULL,
    user_id         INTEGER                                 ,
    reservation_id  INTEGER                                 NOT NULL,
    incident_date   TIMESTAMP WITHOUT TIME ZONE             ,
    comment         VARCHAR(255)                            ,
    CONSTRAINT pk_incident_reports PRIMARY KEY (id),

     CONSTRAINT fk_incident_reports_incident_report_type
        FOREIGN KEY (incident_type_id)
        REFERENCES incident_report_types (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_incident_reports_visitor
        FOREIGN KEY (visitor_id)
        REFERENCES visitors (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_incident_reports_hotel
        FOREIGN KEY (hotel_id)
        REFERENCES hotels (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_incident_reports_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_incident_reports_reservation
        FOREIGN KEY (reservation_id)
        REFERENCES reservations (id)
        ON DELETE CASCADE
);
ALTER TABLE incident_reports
    ADD CONSTRAINT uc_incident_reports_uuid UNIQUE (uuid);
