-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
-----DELETE ME TO APPLY THIS MIGRATION----

CREATE TABLE identification_types
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    name            VARCHAR(255)                            NOT NULL,
    code            VARCHAR(255)                            ,
    issuer          VARCHAR(255)                            ,
    CONSTRAINT pk_identification_types PRIMARY KEY (id)
);
ALTER TABLE identification_types
    ADD CONSTRAINT uc_identification_types_uuid UNIQUE (uuid);
