-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.

-- Create assessment_variance_logs table to track score variances between assessors
CREATE TABLE assessment_variance_logs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN DEFAULT FALSE,

    -- References
    hotel_id           BIGINT                                  NOT NULL,
    form_id            BIGINT                                  NOT NULL,
    form_field_id      BIGINT                                  NOT NULL,
    field_uuid         UUID                                    NOT NULL,
    section_id         BIGINT,

    -- Variance details
    variance_type      VARCHAR(50)                             NOT NULL,
    status             VARCHAR(50)                             NOT NULL DEFAULT 'OPEN',
    score_difference   NUMERIC(10, 2)                          NOT NULL,

    -- Assessor scores involved in variance
    assessor_1_id      BIGINT,
    assessor_1_score   NUMERIC(10, 2),
    assessor_2_id      BIGINT,
    assessor_2_score   NUMERIC(10, 2),
    assessor_3_id      BIGINT,
    assessor_3_score   NUMERIC(10, 2),

    -- Timestamps
    detected_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    resolved_at        TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_assessment_variance_logs PRIMARY KEY (id)
);

-- Add unique constraint
ALTER TABLE assessment_variance_logs
    ADD CONSTRAINT uc_assessment_variance_logs_uuid UNIQUE (uuid);

-- Add foreign key constraints
ALTER TABLE assessment_variance_logs
    ADD CONSTRAINT fk_assessment_variance_logs_hotel_id FOREIGN KEY (hotel_id)
    REFERENCES hotels (id);

ALTER TABLE assessment_variance_logs
    ADD CONSTRAINT fk_assessment_variance_logs_form_id FOREIGN KEY (form_id)
    REFERENCES forms (id);

ALTER TABLE assessment_variance_logs
    ADD CONSTRAINT fk_assessment_variance_logs_form_field_id FOREIGN KEY (form_field_id)
    REFERENCES form_fields (id);

ALTER TABLE assessment_variance_logs
    ADD CONSTRAINT fk_assessment_variance_logs_section_id FOREIGN KEY (section_id)
    REFERENCES form_sections (id);

ALTER TABLE assessment_variance_logs
    ADD CONSTRAINT fk_assessment_variance_logs_assessor_1_id FOREIGN KEY (assessor_1_id)
    REFERENCES assessors (id);

ALTER TABLE assessment_variance_logs
    ADD CONSTRAINT fk_assessment_variance_logs_assessor_2_id FOREIGN KEY (assessor_2_id)
    REFERENCES assessors (id);

ALTER TABLE assessment_variance_logs
    ADD CONSTRAINT fk_assessment_variance_logs_assessor_3_id FOREIGN KEY (assessor_3_id)
    REFERENCES assessors (id);

-- Create indexes for performance
CREATE INDEX idx_variance_logs_hotel_form ON assessment_variance_logs(hotel_id, form_id);
CREATE INDEX idx_variance_logs_status ON assessment_variance_logs(status);
CREATE INDEX idx_variance_logs_field_uuid ON assessment_variance_logs(field_uuid);
CREATE INDEX idx_variance_logs_detected_at ON assessment_variance_logs(detected_at);

-- Add comments
COMMENT ON TABLE assessment_variance_logs IS 'Tracks score variances between assessors for quality control';
COMMENT ON COLUMN assessment_variance_logs.variance_type IS 'Type of variance: SCORE_DIFF, OUTLIER, etc.';
COMMENT ON COLUMN assessment_variance_logs.status IS 'Status: OPEN, RESOLVED, ACKNOWLEDGED';
COMMENT ON COLUMN assessment_variance_logs.score_difference IS 'Maximum difference between assessor scores for this field';
COMMENT ON COLUMN assessment_variance_logs.field_uuid IS 'Denormalized field UUID for faster queries';
