-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
-----DELETE ME TO APPLY THIS MIGRATION----

CREATE TABLE visitors
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    full_name       VARCHAR(255)                            NOT NULL,
    country_id      INTEGER                                 ,
    date_of_birth   DATE                                    ,
    gender          VARCHAR(255)                            ,
    place_of_birth  VARCHAR(255)                            ,
    permanent_physical_address VARCHAR(255)                            ,
    mobile_number   VARCHAR(255)                            ,
    email           VARCHAR(255)                            ,
    identification_type_id INTEGER                                 ,
    id_number       VARCHAR(255)                            ,
    user_id         INTEGER                                 ,
    company_id      INTEGER                                 ,
    passport_border VARCHAR(255)                            ,
    doc_type        VARCHAR(255)                            ,
    doc_entry_point VARCHAR(255)                            ,
    doc_entry_date  TIMESTAMP WITHOUT TIME ZONE             ,
    doc_exit_date   TIMESTAMP WITHOUT TIME ZONE             ,
    doc_residence_place VARCHAR(255)                            ,
    visa_type       VARCHAR(255)                            ,
    visa_number     VARCHAR(255)                            ,
    visa_visit_purpose VARCHAR(255)                            ,
    CONSTRAINT pk_visitors PRIMARY KEY (id),

    CONSTRAINT fk_visitors_country
        FOREIGN KEY (country_id)
        REFERENCES countries (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_visitors_identification_type
        FOREIGN KEY (identification_type_id)
        REFERENCES identification_types (id)
        ON DELETE CASCADE
);
ALTER TABLE visitors
    ADD CONSTRAINT uc_visitors_uuid UNIQUE (uuid);
