-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
-----DELETE ME TO APPLY THIS MIGRATION----

CREATE TABLE reservations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid               UUID                                    NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    is_deleted         BOOLEAN,
    hotel_id        INTEGER                                 NOT NULL,
    room_type_id    INTEGER                                 NOT NULL,
    check_in_date   TIMESTAMP WITHOUT TIME ZONE             ,
    check_out_date  TIMESTAMP WITHOUT TIME ZONE             ,
    visitor_ids     VARCHAR(255)                            ,
    room_number     VARCHAR(255)                            ,
    reservation_code VARCHAR(255)                            ,
    is_checked_out  BOOLEAN                                 ,
    CONSTRAINT pk_reservations PRIMARY KEY (id),

     CONSTRAINT fk_reservations_hotel
        FOREIGN KEY (hotel_id)
        REFERENCES hotels (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reservations_room_type
        FOREIGN KEY (room_type_id)
        REFERENCES room_types (id)
        ON DELETE CASCADE
);
ALTER TABLE reservations
    ADD CONSTRAINT uc_reservations_uuid UNIQUE (uuid);
