-- Create assessor_certificate_evidence table
CREATE TABLE assessor_certificate_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    is_deleted BOOLEAN DEFAULT FALSE,
    
    -- Evidence specific columns
    evidence_description TEXT,
    evidence_type VARCHAR(50),
    upload_status VARCHAR(20) DEFAULT 'UPLOADED',
    assessor_certificate_id BIGINT NOT NULL,
    file_upload_id BIGINT,
    
    CONSTRAINT pk_assessor_certificate_evidence PRIMARY KEY (id),
    CONSTRAINT fk_assessor_certificate_evidence_certificate FOREIGN KEY (assessor_certificate_id) REFERENCES assessor_certificates (id),
    CONSTRAINT fk_assessor_certificate_evidence_file_upload FOREIGN KEY (file_upload_id) REFERENCES file_uploads (id)
);

-- Create indexes
CREATE INDEX idx_assessor_certificate_evidence_certificate_id ON assessor_certificate_evidence (assessor_certificate_id);
CREATE INDEX idx_assessor_certificate_evidence_evidence_type ON assessor_certificate_evidence (evidence_type);
CREATE INDEX idx_assessor_certificate_evidence_upload_status ON assessor_certificate_evidence (upload_status);
CREATE INDEX idx_assessor_certificate_evidence_file_upload_id ON assessor_certificate_evidence (file_upload_id);